CREATE DATABASE University;
GO

USE University;
GO

CREATE TABLE COURSES 
(
    COURSE_ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE GROUPS 
(
    GROUP_ID INT PRIMARY KEY,
    COURSE_ID INT,
    GROUP_NAME VARCHAR(50),
	FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);

CREATE TABLE STUDENTS 
(
    STUDENT_ID INT PRIMARY KEY,
    GROUP_ID INT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
	FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);



