// <auto-generated />
using System;
using B_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B_DataAccess.Migrations
{
    [DbContext(typeof(UniDeskDbContext))]
    partial class UniDeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A_Domain.Models.TeacherCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCourses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            TeacherId = 2
                        },
                        new
                        {
                            CourseId = 1,
                            TeacherId = 3
                        },
                        new
                        {
                            CourseId = 1,
                            TeacherId = 4
                        },
                        new
                        {
                            CourseId = 1,
                            TeacherId = 5
                        },
                        new
                        {
                            CourseId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            TeacherId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            CourseId = 2,
                            TeacherId = 4
                        },
                        new
                        {
                            CourseId = 2,
                            TeacherId = 5
                        },
                        new
                        {
                            CourseId = 3,
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            TeacherId = 3
                        },
                        new
                        {
                            CourseId = 3,
                            TeacherId = 4
                        },
                        new
                        {
                            CourseId = 3,
                            TeacherId = 5
                        },
                        new
                        {
                            CourseId = 4,
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 4,
                            TeacherId = 2
                        },
                        new
                        {
                            CourseId = 4,
                            TeacherId = 3
                        },
                        new
                        {
                            CourseId = 4,
                            TeacherId = 4
                        },
                        new
                        {
                            CourseId = 4,
                            TeacherId = 5
                        },
                        new
                        {
                            CourseId = 5,
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 5,
                            TeacherId = 2
                        },
                        new
                        {
                            CourseId = 5,
                            TeacherId = 3
                        },
                        new
                        {
                            CourseId = 5,
                            TeacherId = 4
                        },
                        new
                        {
                            CourseId = 5,
                            TeacherId = 5
                        });
                });

            modelBuilder.Entity("A_Domain.Models.TutorGroup", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("TutorGroups");

                    b.HasData(
                        new
                        {
                            TutorId = 1,
                            GroupId = 1
                        },
                        new
                        {
                            TutorId = 1,
                            GroupId = 2
                        },
                        new
                        {
                            TutorId = 1,
                            GroupId = 3
                        },
                        new
                        {
                            TutorId = 1,
                            GroupId = 4
                        },
                        new
                        {
                            TutorId = 1,
                            GroupId = 5
                        },
                        new
                        {
                            TutorId = 2,
                            GroupId = 1
                        },
                        new
                        {
                            TutorId = 2,
                            GroupId = 2
                        },
                        new
                        {
                            TutorId = 2,
                            GroupId = 3
                        },
                        new
                        {
                            TutorId = 2,
                            GroupId = 4
                        },
                        new
                        {
                            TutorId = 2,
                            GroupId = 5
                        },
                        new
                        {
                            TutorId = 3,
                            GroupId = 1
                        },
                        new
                        {
                            TutorId = 3,
                            GroupId = 2
                        },
                        new
                        {
                            TutorId = 3,
                            GroupId = 3
                        },
                        new
                        {
                            TutorId = 3,
                            GroupId = 4
                        },
                        new
                        {
                            TutorId = 3,
                            GroupId = 5
                        },
                        new
                        {
                            TutorId = 4,
                            GroupId = 1
                        },
                        new
                        {
                            TutorId = 4,
                            GroupId = 2
                        },
                        new
                        {
                            TutorId = 4,
                            GroupId = 3
                        },
                        new
                        {
                            TutorId = 4,
                            GroupId = 4
                        },
                        new
                        {
                            TutorId = 4,
                            GroupId = 5
                        },
                        new
                        {
                            TutorId = 5,
                            GroupId = 1
                        },
                        new
                        {
                            TutorId = 5,
                            GroupId = 2
                        },
                        new
                        {
                            TutorId = 5,
                            GroupId = 3
                        },
                        new
                        {
                            TutorId = 5,
                            GroupId = 4
                        },
                        new
                        {
                            TutorId = 5,
                            GroupId = 5
                        });
                });

            modelBuilder.Entity("Task10.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This course will teach you how to create phishing software",
                            Name = "C#/.NET"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This course will teach you how to use SQL injections",
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This course will teach you how to bruteforce passwords",
                            Name = "Algorithms and Data Structures"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn cross-site scripting, port scanning, buffer overflow, etc.",
                            Name = "Networks"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Create your rootkit",
                            Name = "OS architecture"
                        });
                });

            modelBuilder.Entity("Task10.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Name = "SR-01"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 4,
                            Name = "SR-02"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Name = "FR-01"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 3,
                            Name = "FR-02"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            Name = "SR-01"
                        });
                });

            modelBuilder.Entity("Task10.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Emily",
                            GroupId = 1,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Emily",
                            GroupId = 4,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "John",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Emily",
                            GroupId = 3,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Sophia",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Emma",
                            GroupId = 4,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Michael",
                            GroupId = 1,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Emma",
                            GroupId = 2,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "William",
                            GroupId = 1,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Sophia",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Sarah",
                            GroupId = 5,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Michael",
                            GroupId = 1,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Michael",
                            GroupId = 4,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "John",
                            GroupId = 4,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "David",
                            GroupId = 2,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Emily",
                            GroupId = 4,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "William",
                            GroupId = 5,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Olivia",
                            GroupId = 5,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Michael",
                            GroupId = 4,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "James",
                            GroupId = 2,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Emma",
                            GroupId = 3,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Michael",
                            GroupId = 2,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Sarah",
                            GroupId = 2,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Sophia",
                            GroupId = 1,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Emma",
                            GroupId = 1,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Emily",
                            GroupId = 4,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Sarah",
                            GroupId = 4,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Michael",
                            GroupId = 3,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "William",
                            GroupId = 3,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Sarah",
                            GroupId = 2,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "David",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "William",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Sophia",
                            GroupId = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "David",
                            GroupId = 1,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Sophia",
                            GroupId = 5,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "John",
                            GroupId = 3,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Emma",
                            GroupId = 5,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Olivia",
                            GroupId = 3,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Sarah",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Olivia",
                            GroupId = 2,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Emma",
                            GroupId = 2,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "William",
                            GroupId = 3,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "William",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "John",
                            GroupId = 1,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Sophia",
                            GroupId = 1,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "John",
                            GroupId = 1,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Sarah",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "James",
                            GroupId = 3,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Emily",
                            GroupId = 5,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Emma",
                            GroupId = 4,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Sophia",
                            GroupId = 5,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Emma",
                            GroupId = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "James",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Michael",
                            GroupId = 3,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Emma",
                            GroupId = 2,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "John",
                            GroupId = 3,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Olivia",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Sophia",
                            GroupId = 4,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Sophia",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Emma",
                            GroupId = 1,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "John",
                            GroupId = 3,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "John",
                            GroupId = 2,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Sophia",
                            GroupId = 1,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Sophia",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "William",
                            GroupId = 4,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "William",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Michael",
                            GroupId = 3,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Sarah",
                            GroupId = 2,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Sarah",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Sarah",
                            GroupId = 1,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Sophia",
                            GroupId = 2,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Olivia",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "William",
                            GroupId = 1,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "William",
                            GroupId = 1,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Michael",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "John",
                            GroupId = 5,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Emma",
                            GroupId = 2,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Olivia",
                            GroupId = 2,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "David",
                            GroupId = 3,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "John",
                            GroupId = 4,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Michael",
                            GroupId = 5,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Emily",
                            GroupId = 3,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Emma",
                            GroupId = 1,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "John",
                            GroupId = 2,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Emma",
                            GroupId = 1,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Emma",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Emma",
                            GroupId = 1,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "James",
                            GroupId = 5,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "John",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Sophia",
                            GroupId = 1,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Emma",
                            GroupId = 3,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Emily",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Sarah",
                            GroupId = 4,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Michael",
                            GroupId = 3,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "David",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "David",
                            GroupId = 1,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Sarah",
                            GroupId = 4,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "David",
                            GroupId = 1,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "John",
                            GroupId = 2,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "John",
                            GroupId = 3,
                            LastName = "Moore"
                        });
                });

            modelBuilder.Entity("Task10.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ivan",
                            LastName = "Ivanov"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Petr",
                            LastName = "Petrov"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Michael",
                            LastName = "Michaelson"
                        });
                });

            modelBuilder.Entity("Task10.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId")
                        .IsUnique()
                        .HasFilter("[TeacherId] IS NOT NULL");

                    b.ToTable("Tutors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            TeacherId = 5
                        });
                });

            modelBuilder.Entity("A_Domain.Models.TeacherCourse", b =>
                {
                    b.HasOne("Task10.Models.Course", "Course")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task10.Models.Teacher", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("A_Domain.Models.TutorGroup", b =>
                {
                    b.HasOne("Task10.Models.Group", "Group")
                        .WithMany("TutorGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task10.Models.Tutor", "Tutor")
                        .WithMany("TutorGroups")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Task10.Models.Group", b =>
                {
                    b.HasOne("Task10.Models.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Task10.Models.Student", b =>
                {
                    b.HasOne("Task10.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Task10.Models.Tutor", b =>
                {
                    b.HasOne("Task10.Models.Teacher", "Teacher")
                        .WithOne("Tutor")
                        .HasForeignKey("Task10.Models.Tutor", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Task10.Models.Course", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("Task10.Models.Group", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TutorGroups");
                });

            modelBuilder.Entity("Task10.Models.Teacher", b =>
                {
                    b.Navigation("TeacherCourses");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Task10.Models.Tutor", b =>
                {
                    b.Navigation("TutorGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
