// <auto-generated />
using B_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace B_DataAccess.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20230607211947__initCreateDb")]
    partial class _initCreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "C#/.NET",
                            Description = "This course will teach you how to create phishing software"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "SQL",
                            Description = "This course will teach you how to use SQL injections"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Algorithms and Data Structures",
                            Description = "This course will teach you how to bruteforce passwords"
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Networks",
                            Description = "Learn cross-site scripting, port scanning, buffer overflow, etc."
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "OS architecture",
                            Description = "Create your rootkit"
                        });
                });

            modelBuilder.Entity("Domain.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            GroupName = "SR-01"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 4,
                            GroupName = "SR-02"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            GroupName = "FR-01"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 3,
                            GroupName = "FR-02"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            GroupName = "SR-01"
                        });
                });

            modelBuilder.Entity("Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            GroupId = 4,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Olivia",
                            GroupId = 3,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "John",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Michael",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "James",
                            GroupId = 4,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Sarah",
                            GroupId = 3,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "James",
                            GroupId = 4,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "William",
                            GroupId = 2,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "John",
                            GroupId = 1,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Michael",
                            GroupId = 1,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Olivia",
                            GroupId = 4,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Emily",
                            GroupId = 3,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Emily",
                            GroupId = 5,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "David",
                            GroupId = 4,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Emily",
                            GroupId = 5,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Michael",
                            GroupId = 3,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Olivia",
                            GroupId = 3,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Michael",
                            GroupId = 5,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "David",
                            GroupId = 5,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Emily",
                            GroupId = 4,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Emily",
                            GroupId = 3,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "William",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Sarah",
                            GroupId = 3,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Sarah",
                            GroupId = 3,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "William",
                            GroupId = 1,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "James",
                            GroupId = 4,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Michael",
                            GroupId = 5,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "William",
                            GroupId = 5,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Olivia",
                            GroupId = 3,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Sophia",
                            GroupId = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "William",
                            GroupId = 5,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Sarah",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Emily",
                            GroupId = 4,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Emily",
                            GroupId = 2,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "John",
                            GroupId = 4,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "John",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "James",
                            GroupId = 1,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Sarah",
                            GroupId = 5,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Sophia",
                            GroupId = 4,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Michael",
                            GroupId = 4,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "John",
                            GroupId = 3,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Sarah",
                            GroupId = 4,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "William",
                            GroupId = 4,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Emily",
                            GroupId = 3,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Emma",
                            GroupId = 2,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Sophia",
                            GroupId = 3,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "David",
                            GroupId = 2,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "James",
                            GroupId = 4,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Sarah",
                            GroupId = 1,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "James",
                            GroupId = 1,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Emma",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Sarah",
                            GroupId = 5,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "James",
                            GroupId = 5,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Emma",
                            GroupId = 2,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "John",
                            GroupId = 5,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Olivia",
                            GroupId = 5,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Sophia",
                            GroupId = 1,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Emily",
                            GroupId = 3,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "David",
                            GroupId = 3,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "William",
                            GroupId = 1,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Olivia",
                            GroupId = 1,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Olivia",
                            GroupId = 4,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Emma",
                            GroupId = 5,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Emily",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Olivia",
                            GroupId = 1,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "John",
                            GroupId = 3,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Emma",
                            GroupId = 1,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Emily",
                            GroupId = 3,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "John",
                            GroupId = 4,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "John",
                            GroupId = 1,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Michael",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Sophia",
                            GroupId = 4,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Emily",
                            GroupId = 1,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "David",
                            GroupId = 3,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "John",
                            GroupId = 1,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Michael",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Olivia",
                            GroupId = 2,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Emma",
                            GroupId = 3,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "James",
                            GroupId = 4,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Olivia",
                            GroupId = 4,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Emma",
                            GroupId = 5,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Sophia",
                            GroupId = 4,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "William",
                            GroupId = 4,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Emily",
                            GroupId = 3,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Michael",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Sophia",
                            GroupId = 4,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "David",
                            GroupId = 5,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "William",
                            GroupId = 4,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "William",
                            GroupId = 3,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Olivia",
                            GroupId = 2,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "John",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Emily",
                            GroupId = 4,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Olivia",
                            GroupId = 3,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Michael",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Sarah",
                            GroupId = 3,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Emma",
                            GroupId = 1,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Olivia",
                            GroupId = 5,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "James",
                            GroupId = 5,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "James",
                            GroupId = 2,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Emily",
                            GroupId = 2,
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("Domain.Group", b =>
                {
                    b.HasOne("Domain.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Student", b =>
                {
                    b.HasOne("Domain.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Domain.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Domain.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
